### ISSUE TITLE
Desktop Version Portfolio Issue #1

### ISSUE THREAD

**Issue by sheylaPozo** [andersonlebon/Portfolio-w2#5]
## CONGRATULATIONS :clap: :+1:  :1st_place_medal: :1st_place_medal: 
You have done a great job +1 but here are somethings you can improve:

- In the footer, there's a line that says"I'm always interested in hearing about new projects, so if you'd like to chat please get in touch." so there was a little mistake in the spelling of "always" there, so just switch it up for the correct word to improve the project's view. 

And everything else was too perfect to add anything in advance, it was a very great project.

HAPPY CODING!! :100:

**Comment by andersonlebon** [comment]
## Thanks for the Suggestion
